version: '3'

services:
    php73:
        build: ./php73
        volumes:
          - "/mnt/eb6ce2fb-3c58-4876-baf6-ae932743816f/projects:/usr/local/var/www:cached"
          - "/ssh:/root/.ssh"
          - "/composer:/root/.composer"
          - ./php73/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
          - ./php73/zsh/.zshrc:/root/.zshrc
          - ./php73/zsh/.zsh_history:/root/.zsh_history
        environment:
        - ZSH_THEME=afowler    
    php74: 
      build: ./php74
      volumes: 
        - "/mnt/eb6ce2fb-3c58-4876-baf6-ae932743816f/projects:/usr/local/var/www:cached"    
    mysql:
      build: ./mysql
      command: "--innodb_use_native_aio=0"
      ports:
        - "3306:3306"
      volumes:
        - "mysql-sync:/var/lib/mysql:cached"
      environment:
        - MYSQL_ROOT_PASSWORD=root123
        - MYSQL_USER=mage
        - MYSQL_PASSWORD=mage
    redis:
        image: redis
        ports:
          - "6379"
    nginx:
        build: ./nginx
        volumes:
          - "/mnt/eb6ce2fb-3c58-4876-baf6-ae932743816f/projects:/usr/local/var/www:cached"    
        ports: 
          - "80:80"    
        depends_on:
          - "strapi-hieunguyen-dev"
          - "strapi-merakiweddingplanner"
          - "strapi-merakicommerce"           
    elasticsearch:
        image: elasticsearch:7.14.0
        volumes: 
          - elasticdata:/usr/share/elasticsearch/data
        ports:
          - "9200:9200"
          - "9300:9300"
        environment:
        - discovery.type=single-node
        - http.cors.allow-origin=/.*/
        - http.cors.enabled=true
        tty: true
        mem_limit: 3g
    meilisearch:
        image: getmeili/meilisearch:latest
        volumes: 
          - /mnt/eb6ce2fb-3c58-4876-baf6-ae932743816f/projects/meilisearch25/data.ms:/data.ms
        environment: 
          - MEILI_MASTER_KEY=mobelazz
    strapi-merakicommerce:
        image: strapi/strapi
        environment:
          - DATABASE_CLIENT=mysql
          - DATABASE_HOST=mysql
          - DATABASE_PORT=3306
          - DATABASE_NAME=strapi-merakicommerce
          - DATABASE_USERNAME=strapi
          - DATABASE_PASSWORD=toni-0suction-2Science
          - DATABASE_SSL=false
        volumes:
          - /mnt/eb6ce2fb-3c58-4876-baf6-ae932743816f/projects/strapi-merakicommerce-com:/srv/app        
    strapi-hieunguyen-dev:
        image: strapi/strapi
        environment:
          - DATABASE_CLIENT=mysql
          - DATABASE_HOST=mysql
          - DATABASE_PORT=3306
          - DATABASE_NAME=strapi-hieunguyen-dev
          - DATABASE_USERNAME=strapi
          - DATABASE_PASSWORD=toni-0suction-2Science
          - DATABASE_SSL=false
        volumes:
          - /mnt/eb6ce2fb-3c58-4876-baf6-ae932743816f/projects/strapi-hieunguyen-dev:/srv/app
        depends_on:
          - "mysql"
    strapi-merakiweddingplanner:
        image: strapi/strapi
        environment:
          - DATABASE_CLIENT=mysql
          - DATABASE_HOST=mysql
          - DATABASE_PORT=3306
          - DATABASE_NAME=strapi-merakiweddingplanner
          - DATABASE_USERNAME=strapi
          - DATABASE_PASSWORD=toni-0suction-2Science
          - DATABASE_SSL=false
        volumes:
          - /mnt/eb6ce2fb-3c58-4876-baf6-ae932743816f/projects/strapi-merakiweddingplanner:/srv/app
        depends_on:
          - "mysql"
    strapi-mobelaris:
        image: strapi/strapi
        environment:
          - DATABASE_CLIENT=mysql
          - DATABASE_HOST=206.189.33.14
          - DATABASE_PORT=3306
          - DATABASE_NAME=strapimobelaris
          - DATABASE_USERNAME=strapimobel_usr
          - DATABASE_PASSWORD=2xUaKSvV9Kd4waNw
          - DATABASE_SSL=false
        volumes:
          - /mnt/eb6ce2fb-3c58-4876-baf6-ae932743816f/projects/strapi-mobelaris:/srv/app    
    myrecvan.hieunguyen.dev:
        image: wordpress
        restart: always
        environment:
          WORDPRESS_DB_HOST: mysql
          WORDPRESS_DB_USER: myrecvan
          WORDPRESS_DB_PASSWORD: who-campfire7-9Ageless
          WORDPRESS_DB_NAME: myrecvan
        volumes:
          - /mnt/eb6ce2fb-3c58-4876-baf6-ae932743816f/projects/myrecvan:/var/www/html
    varnish:
        build: ./varnish          
        depends_on:
          - "nginx" 
volumes:
  mysql-sync:
  mysql8-sync:  
  elasticdata:
  searchdata:
  manticoresearch:
  nextcloud:
  wordpress:
  db:
