version: '3'

services:
    php73:
        build: ./php73
        volumes:
          - "/home/hieunguyen/docker-local/projects:/usr/local/var/www:cached"
          - "/ssh:/root/.ssh"
          - "/composer:/root/.composer"
          - ./php73/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
          - ./php73/zsh/.zshrc:/root/.zshrc
          - ./php73/zsh/.zsh_history:/root/.zsh_history
        environment:
        - ZSH_THEME=afowler
    mysql:
        build: ./mysql
        command: "--innodb_use_native_aio=0"
        ports:
          - "3306:3306"
        volumes:
          - "mysql-sync:/var/lib/mysql:cached"
        environment:
          - MYSQL_ROOT_PASSWORD=root123
          - MYSQL_USER=mage
          - MYSQL_PASSWORD=mage
    redis:
        image: redis
        ports:
          - "6379"
    nginx:
        build: ./nginx
        volumes:
          - "/home/hieunguyen/docker-local/projects:/usr/local/var/www:cached"
        ports:
          - "80:80"
          - "443:443"
    elasticsearch:
        image: elasticsearch:7.9.1
        ports:
          - "9200:9200"
          - "9300:9300"
        environment:
        - discovery.type=single-node
        tty: true
volumes:
  mysql-sync:
