version: '3'

services:
    php73:
        build: ./php73
        volumes:
          - "/home/hieunguyen/docker-local/projects:/usr/local/var/www:cached"
          - "/home/gx71orx0jtq4/public_html:/home/gx71orx0jtq4/public_html"
          - "/ssh:/root/.ssh"
          - "/composer:/root/.composer"
          - ./php73/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
          - ./php73/zsh/.zshrc:/root/.zshrc
          - ./php73/zsh/.zsh_history:/root/.zsh_history
        environment:
        - ZSH_THEME=afowler    
    php74: 
      build: ./php74
      volumes: 
        - "/home/hieunguyen/docker-local/projects:/usr/local/var/www:cached"    
    php81: 
      build: ./php81
      volumes: 
        - "/home/hieunguyen/docker-local/projects:/usr/local/var/www:cached"    
    mysql:
      build: ./mysql
      command: "--innodb_use_native_aio=0"
      ports:
        - "3306:3306"
      volumes:
        - "mysql-sync:/var/lib/mysql:cached"
      environment:
        - MYSQL_ROOT_PASSWORD=root123
        - MYSQL_USER=mage
        - MYSQL_PASSWORD=mage
    redis:
        image: redis
        ports:
          - "6379:6379"
    nginx:
        build: ./nginx
        volumes:
          - "/home/hieunguyen/docker-local/projects:/usr/local/var/www:cached"              
          - "/home/gx71orx0jtq4/public_html:/home/gx71orx0jtq4/public_html"
        
    elasticsearch:
        image: elasticsearch:7.14.0
        volumes: 
          - elasticdata:/usr/share/elasticsearch/data
        ports:
          - "9200:9200"
          - "9300:9300"
        environment:
        - discovery.type=single-node
        - http.cors.allow-origin=/.*/
        - http.cors.enabled=true
        tty: true
        mem_limit: 3g
    meilisearch:
        image: getmeili/meilisearch:v0.28.1
        volumes: 
          - meilisearchdata:/data.ms
        environment: 
          - MEILI_MASTER_KEY=mobelazz   
    myrecvan.hieunguyen.dev:
        image: wordpress
        restart: always
        environment:
          WORDPRESS_DB_HOST: mysql
          WORDPRESS_DB_USER: myrecvan
          WORDPRESS_DB_PASSWORD: who-campfire7-9Ageless
          WORDPRESS_DB_NAME: myrecvan
        volumes:
          - /mnt/eb6ce2fb-3c58-4876-baf6-ae932743816f/projects/myrecvan:/var/www/html
    varnish:
        build: ./varnish                  
        depends_on:
          - "nginx"
        ports: 
          - "80:80"   
volumes:
  mysql-sync:
  mysql8-sync:  
  elasticdata:
  searchdata:
  manticoresearch:
  nextcloud:
  wordpress:
  db:
  meilisearchdata:
