version: '3'

services:
    php73:
        build: ./php73
        volumes:
          - "/home/hieunguyen/docker-local/projects:/usr/local/var/www:cached"
          - "/ssh:/root/.ssh"
          - "/composer:/root/.composer"
          - ./php73/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
          - ./php73/zsh/.zshrc:/root/.zshrc
          - ./php73/zsh/.zsh_history:/root/.zsh_history
        environment:
        - ZSH_THEME=afowler    
    php74: 
      build: ./php74
      volumes: 
        - "/home/hieunguyen/docker-local/projects:/usr/local/var/www:cached"    
    mysql:
      build: ./mysql
      command: "--innodb_use_native_aio=0"
      ports:
        - "3306:3306"
      volumes:
        - "mysql-sync:/var/lib/mysql:cached"
      environment:
        - MYSQL_ROOT_PASSWORD=root123
        - MYSQL_USER=mage
        - MYSQL_PASSWORD=mage
    redis:
        image: redis
        ports:
          - "6379"
    nginx:
        build: ./nginx
        volumes:
          - "/home/hieunguyen/docker-local/projects:/usr/local/var/www:cached"
    varnish:
        build: ./varnish          
        ports: 
          - "80:80"
        depends_on:
          - "nginx"        
    elasticsearch:
        image: elasticsearch:7.14.0
        volumes: 
          - elasticdata:/usr/share/elasticsearch/data
        ports:
          - "9200:9200"
          - "9300:9300"
        environment:
        - discovery.type=single-node
        - http.cors.allow-origin=/.*/
        - http.cors.enabled=true
        tty: true
        mem_limit: 3g
    meilisearch:
        image: getmeili/meilisearch
        volumes: 
          - ./projects/meilisearch/data.ms:/data.ms
        environment: 
          - MEILI_MASTER_KEY=mobelazz
    strapi-merakicommerce:
        image: strapi/strapi
        environment:
          - DATABASE_CLIENT=mysql
          - DATABASE_HOST=mysql
          - DATABASE_PORT=3306
          - DATABASE_NAME=strapi-merakicommerce
          - DATABASE_USERNAME=strapi
          - DATABASE_PASSWORD=toni-0suction-2Science
          - DATABASE_SSL=false
        volumes:
          - ./project/strapi-merakicommerce:/srv/app
        depends_on:
          - "mysql"
    strapi-hieunguyen-dev:
        image: strapi/strapi
        environment:
          - DATABASE_CLIENT=mysql
          - DATABASE_HOST=mysql
          - DATABASE_PORT=3306
          - DATABASE_NAME=strapi-hieunguyen-dev
          - DATABASE_USERNAME=strapi
          - DATABASE_PASSWORD=toni-0suction-2Science
          - DATABASE_SSL=false
        volumes:
          - ./projects/strapi-hieunguyen-dev:/srv/app
        depends_on:
          - "mysql"
    search:
        image: typesense/typesense:0.9.2
        volumes:
          - searchdata:/data
        ports:
          - 8108:8108
        environment:
          API_KEY: sdasn2@#!
        entrypoint: sh -c "/opt/typesense-server --data-dir /data --api-key=$${API_KEY}"
    manticoresearch:
        image: manticoresearch/manticore
        ports: 
          - 9306:9306
          - 9308:9308        
        volumes:
          - manticoresearch:/var/lib/manticore
    elasticvue:
        image: cars10/elasticvue
        ports: 
          - 8080:8080
        
volumes:
  mysql-sync:
  mysql8-sync:  
  elasticdata:
  searchdata:
  manticoresearch:
  nextcloud:
  wordpress:
  db:
