version: '3'

services:
    magentophp70:
        build: ./docker-magento-php70
        volumes:
          - "/home/hieunguyen/docker-local/projects:/usr/local/var/www:cached"
          - "/ssh:/root/.ssh"
          - "/composer:/root/.composer"
          - ./docker-magento-php70/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
          - ./docker-magento-php70/conf/cacert.pem:/usr/local/etc/php/cacert.pem
          - ./docker-magento-php70/zsh/.zshrc:/root/.zshrc
          - ./docker-magento-php70/zsh/.zsh_history:/root/.zsh_history
        environment:
          - ZSH_THEME=afowler
          - PHP_MEMORY_LIMIT=3G

    php72:
        build: ./php72
        volumes:
          - "/home/hieunguyen/docker-local/projects:/usr/local/var/www:cached"
          - "/ssh:/root/.ssh"
          - "/composer:/root/.composer"
          - ./php72/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
          - ./php72/zsh/.zshrc:/root/.zshrc
          - ./php72/zsh/.zsh_history:/root/.zsh_history
        environment:
        - ZSH_THEME=afowler
    php73:
        build: ./php73
        volumes:
          - "/home/hieunguyen/docker-local/projects:/usr/local/var/www:cached"
          - "/ssh:/root/.ssh"
          - "/composer:/root/.composer"
          - ./php73/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
          - ./php73/zsh/.zshrc:/root/.zshrc
          - ./php73/zsh/.zsh_history:/root/.zsh_history
        environment:
        - ZSH_THEME=afowler
    php71:
        build: ./docker-magento-php71
        volumes:
          - "/home/hieunguyen/docker-local/projects:/usr/local/var/www:cached"
          - "/ssh:/root/.ssh"
          - "/composer:/root/.composer"
          - ./docker-magento-php71/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
          - ./docker-magento-php71/zsh/.zshrc:/root/.zshrc
          - ./docker-magento-php71/zsh/.zsh_history:/root/.zsh_history
        environment:
        - ZSH_THEME=afowler
    mysql:
        build: ./mysql
        command: "--innodb_use_native_aio=0"
        ports:
          - "3306:3306"
        volumes:
          - "mysql-sync:/var/lib/mysql:cached"
        environment:
          - MYSQL_ROOT_PASSWORD=root123
          - MYSQL_USER=mage
          - MYSQL_PASSWORD=mage
    redis:
        image: redis
        ports:
          - "6379"
    nginx:
        build: ./nginx
        volumes:
          - "/home/hieunguyen/docker-local/projects:/usr/local/var/www:cached"
        ports:
          - "80:80"
          - "443:443"
    elasticsearch:
        image: elasticsearch:7.9.1
        ports:
          - "9200:9200"
          - "9300:9300"
        environment:
        - discovery.type=single-node
        tty: true
    rabbitmq:
        image: rabbitmq:3-management
        ports:
          - "5672:5672"
        environment:
          - RABBITMQ_DEFAULT_USER=user
          - RABBITMQ_DEFAULT_PASS=password
        tty: true
    ubuntu:
        build: ./vnc
        ports:
          - "5900:5900"
        tty: true
volumes:
  mysql-sync:
