version: '3'

services:
    magentophp70:
        build: ./docker-magento-php70
        volumes:
          - "/home/hieunguyen/docker-local/projects:/usr/local/var/www:cached"
          - "/ssh:/root/.ssh"
          - "/composer:/root/.composer"
          - ./docker-magento-php70/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
          - ./docker-magento-php70/conf/cacert.pem:/usr/local/etc/php/cacert.pem
          - ./docker-magento-php70/zsh/.zshrc:/root/.zshrc
          - ./docker-magento-php70/zsh/.zsh_history:/root/.zsh_history
        environment:
          - ZSH_THEME=afowler
          - PHP_MEMORY_LIMIT=3G

    php72:
        build: ./php72
        volumes:
          - "/home/hieunguyen/docker-local/projects:/usr/local/var/www:cached"
          - "/ssh:/root/.ssh"
          - "/composer:/root/.composer"
          - ./php72/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
          - ./php72/zsh/.zshrc:/root/.zshrc
          - ./php72/zsh/.zsh_history:/root/.zsh_history
        environment:
        - ZSH_THEME=afowler
    php71:
        build: ./docker-magento-php71
        volumes:
          - "/home/hieunguyen/docker-local/projects:/usr/local/var/www:cached"
          - "/ssh:/root/.ssh"
          - "/composer:/root/.composer"
          - ./docker-magento-php71/conf/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
          - ./docker-magento-php71/zsh/.zshrc:/root/.zshrc
          - ./docker-magento-php71/zsh/.zsh_history:/root/.zsh_history
        environment:
        - ZSH_THEME=afowler
    mysql:
        build: ./mysql
        command: "--innodb_use_native_aio=0"
        ports:
          - "3306:3306"
        volumes:
          - "mysql-sync:/var/lib/mysql:cached"
        environment:
          - MYSQL_ROOT_PASSWORD=root123
          - MYSQL_USER=mage
          - MYSQL_PASSWORD=mage
    redis:
        image: redis
        ports:
          - "6379"
    nginx:
        build: ./nginx
        volumes:
          - "/home/hieunguyen/docker-local/projects:/usr/local/var/www:cached"
        ports:
          - "80:80"
          - "443:443"
    elasticsearch:
        image: vortexcommerce/elasticsearch:5.6.8
        ports:
          - "9200:9200"
          - "9300:9300"
        environment:
          - bootstrap.memory_lock=true
          - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
        ulimits:
          memlock:
            soft: -1
            hard: -1
    fastpanel:
      container_name: letsencrypt
      build:
        context: ./fastpanel
      image: hieunguyen/fastpanel
      command: /bin/true
      tty: true
    letsencrypt:
      container_name: letsencrypt
      build:
        context: ./letsencrypt
        args:
          SHOP_URI: 'magento233.m2loc'
      image: hieunguyen/letsencrypt
      command: /bin/true
      volumes:
        - letsencrypt_certs:/etc/letsencrypt
        - letsencrypt_www:/var/www/letsencrypt
      tty: true

volumes:
  mysql-sync:
  letsencrypt_certs:
  letsencrypt_www:
